version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api-rest:
    container_name: api-rest
    build:
      context: ./api-rest
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=pguser
      - DATABASE_PASSWORD=pgpass
      - DATABASE_NAME=pgdb
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - GRPC_SERVICE_URL=grpc-service:50051
    restart: always
    depends_on:
      - db
      - minio
      - grpc-service

  api-graphql:
    container_name: api-graphql
    build:
      context: ./api-graphql
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - GRPC_SERVICE_URL=grpc-service:50051
    depends_on:
      - grpc-service

  grpc-service:
    container_name: grpc-service
    build:
      context: ./grpc-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=pguser
      - DATABASE_PASSWORD=pgpass
      - DATABASE_NAME=pgdb
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
    restart: always
    depends_on:
      - db
      - minio

  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

volumes:
  postgres_data:
  minio_data:
