version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api-rest:
    container_name: api-rest
    build:
      context: ./api-rest
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=pguser
      - DATABASE_PASSWORD=pgpass
      - DATABASE_NAME=pgdb
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - MINIO_EXTERNAL_ENDPOINT=localhost
      - GRPC_SERVICE_URL=grpc-service:50051
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ISSUER_URL=http://localhost:8080
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=myclient
    volumes:
      - ./api-rest:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - db
      - minio
      - grpc-service
      - keycloak

  api-graphql:
    container_name: api-graphql
    build:
      context: ./api-graphql
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=pguser
      - DATABASE_PASSWORD=pgpass
      - DATABASE_NAME=pgdb
      - GRPC_SERVICE_URL=grpc-service:50051
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ISSUER_URL=http://localhost:8080
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=myclient
      - NODE_ENV=production
    volumes:
      - ./api-graphql:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - grpc-service
      - db
      - keycloak

  grpc-service:
    container_name: grpc-service
    build:
      context: ./grpc-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
      - "50052:50052"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=pguser
      - DATABASE_PASSWORD=pgpass
      - DATABASE_NAME=pgdb
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - MINIO_EXTERNAL_ENDPOINT=localhost
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ISSUER_URL=http://localhost:8080
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=myclient
    volumes:
      - ./grpc-service:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - db
      - minio

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
        - "9000:9000"
        - "9090:9090"
    volumes:
      - minio_data:/data
    command:
    - server
    - /data
    - --console-address
    - ":9090"
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
    - "8080:8080"

volumes:
  postgres_data:
  minio_data:
